# Generated by Django 3.2.6 on 2021-08-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='user',
            new_name='username',
        ),
    ]
