# Generated by Django 3.2.6 on 2021-08-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_rename_user_pessoa_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='username',
        ),
    ]
