# Generated by Django 3.2.6 on 2021-09-06 22:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0017_remove_pessoa_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
