# Generated by Django 3.2.6 on 2021-09-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0019_alter_pessoa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='documento',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
