# Generated by Django 3.2.6 on 2021-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0021_alter_pessoa_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data',
            field=models.DateTimeField(default=None),
        ),
    ]
