# Generated by Django 3.2.6 on 2021-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0022_pessoa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
