# Generated by Django 3.2.6 on 2021-09-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0023_alter_pessoa_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='data',
        ),
    ]
