# Generated by Django 3.2.6 on 2021-08-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210816_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nome',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
