# Generated by Django 3.2.6 on 2021-08-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USer',
        ),
    ]
