# Generated by Django 3.2.6 on 2021-08-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0002_veiculo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
