# Generated by Django 3.2.6 on 2021-08-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_rename_user_pessoa_username'),
        ('garagem', '0007_alter_veiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nome_pessoa', to='pessoa.pessoa'),
        ),
    ]
