# Generated by Django 3.2.6 on 2021-08-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_remove_pessoa_username'),
        ('garagem', '0009_alter_veiculo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoa.pessoa'),
        ),
    ]
