# Generated by Django 3.2.6 on 2021-08-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0010_alter_veiculo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='usuario',
            new_name='proprietario',
        ),
    ]
