# Generated by Django 3.2.6 on 2021-08-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0012_veiculo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='user',
        ),
    ]
