# Generated by Django 3.2.6 on 2021-09-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0016_alter_veiculo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='access_level',
        ),
    ]
