# Generated by Django 3.2.6 on 2021-09-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0017_remove_veiculo_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
