# Generated by Django 3.2.6 on 2021-09-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0018_veiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7),
        ),
    ]
