# Generated by Django 3.2.6 on 2021-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0022_veiculo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
