# Generated by Django 3.2.6 on 2021-09-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0025_veiculo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
